# --- PIPELINE CONFIGURATION ---
shadowMapResolution=2048
shadowDistance=128.0

# --- SCREEN ---
screen.main=celLevels, saturationFactor, gamma, outlineThickness, depthThreshold, normalThreshold, shadowThreshold, shadowTint, lightIntensity, debugMode

# --- OPTIONS ---
option.celLevels=4.0
option.celLevels.comment=Amount of quantization bands for shading
option.celLevels.min=2.0
option.celLevels.max=12.0
option.celLevels.step=1.0

option.saturationFactor=1.2
option.saturationFactor.min=0.0
option.saturationFactor.max=4.0

option.gamma=0.8
option.gamma.min=0.1
option.gamma.max=2.0

option.outlineThickness=0
option.outlineThickness.min=0.0
option.outlineThickness.max=4.0

option.depthThreshold=0.1
option.depthThreshold.min=0.01
option.depthThreshold.max=1.0

option.normalThreshold=0.2
option.normalThreshold.min=0.01
option.normalThreshold.max=1.0

option.shadowThreshold=0.1
option.shadowThreshold.min=0.0
option.shadowThreshold.max=1.0

option.lightIntensity=1.0
option.lightIntensity.min=0.0
option.lightIntensity.max=5.0

option.debugMode=3
option.debugMode.min=0
option.debugMode.max=3
