#Minecraft Settings
oldLighting = true
underwaterOverlay = false

frustum.culling = true
shadow.culling = false
variable.float.tempVal = min(1.0,temperature*4.0)
uniform.float.BiomeTemp = tempVal
#1.0 - tempVal*tempVal*(3.0-2.0*tempVal)

#Block AO is written to color.a when true
separateAo = true


moon = true
stars = false
vignette = false
dynamicHandLight = true
shadowTranslucent = true
backFace.translucent = true

shadowBlockEntities = true

sliders = BaseQuality LightBlackLevel LightWhiteLevel GlowBrightness FogAmount DetailBlurring EdgeShading ShadowSampleCount shadowMapResolution DebugView SaturationBoost ContrastBoost WhiteEdgeEntities WhiteEdgeFoliage BorderThickness DepthThreshold NormalThreshold CelLevels HuePreserve TopEdgeFade SoftLight ColorSoftness BorderOpacity BorderSoftness HandDrawn ColorPop ValueComp HaloThickness ObjectShrink EnableFoliageBorder PastelSaturation PastelWash PastelShiftR PastelShiftG PastelShiftB SoftWhiteMix EnableBorders EnableDistanceDarken EnableExtraDetail AirDepthCutoff ExtraDetailStrength ForceFullLight DisableShadows LightSoftness WaterSparkle LeafSwayStrength LeafSwaySpeed WarmTintMix NightDarkness FastMode

screen.columns = 2
screen = PROC_PROMO BaseQuality <empty> <empty> LightBlackLevel LightWhiteLevel GlowBrightness FogAmount DetailBlurring EdgeShading UnderWaterBlur SolidLeaves <empty> <empty> ShadowSampleCount shadowMapResolution DebugView WorldColor SaturationBoost ContrastBoost WhiteEdgeEntities WhiteEdgeFoliage BorderThickness DepthThreshold NormalThreshold CelLevels HuePreserve TopEdgeFade SoftLight ColorSoftness BorderOpacity BorderSoftness HandDrawn ColorPop ValueComp HaloThickness ObjectShrink EnableFoliageBorder PastelSaturation PastelWash PastelShiftR PastelShiftG PastelShiftB SoftWhiteMix EnableBorders EnableDistanceDarken EnableExtraDetail AirDepthCutoff ExtraDetailStrength ForceFullLight DisableShadows LightSoftness WaterSparkle LeafSwayStrength LeafSwaySpeed WarmTintMix CandyMode EnableOreGlow NightDarkness FastMode

entities.glowing.depth = false

alphaTest.gbuffers_terrain = off
# alphaTest.gbuffers_entities = off
alphaTest.gbuffers_skytextured = off
alphaTest.gbuffers_skybasic = off
alphaTest.gbuffers_weather = off
alphaTest.gbuffers_armor_glint = off

beacon.beam.depth = false
beacon.beam.shadow = false
entities.glowing.depth = false

# -- -- --

variable.float.texelSizeX = 1.0/viewWidth
variable.float.texelSizeY = 1.0/viewHeight
uniform.vec2.texelSize=vec2(texelSizeX,texelSizeY)

uniform.float.invFar = 1.0/far

# -- -- --
